import 'package:flutter/material.dart';

const districts = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticaloa',
  'Colombo',
  'Galle',
  'Gampaha',
  'Hambantota',
  'Jaffna',
  'Kalutara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matale',
  'Matara',
  'Monaragala',
  'Mullaitivu',
  'Nuwara Eliya',
  'Polonnaruwa',
  'Puttalam',
  'Ratnapura',
  'Trincomalee',
  'Vavuniya'
];

const priceRange = [
  "1000",
  "2000",
  "5000",
  "10000",
  "20000",
  "50000",
  "100000"
];

const weightRange = ["< 30", "30-60", "60-90", "90 <"];

const cropTypes = [
  "Carrot",
  "Leeks",
  "Cabbage",
  "Raddish",
  "Beetroot",
  "Potatoes",
  "Knolkhol",
  'Pepper',
  'Lettuce',
  'Tomato',
  'Capsicum'
];

const groupType = ['Single', 'Group'];

const vegetables = [
  "Carrot (Karot)",
  "Tomato (Thakkali)",
  "Cucumber (Pipinna)",
  "Beans (Bonchi)",
  "Cabbage (Gova)",
  "Cauliflower (Mal Gova)",
  "Brinjal/Eggplant (Wambatu)",
  "Bitter Gourd (Karavila)",
  "Pumpkin (Wattakka)",
  "Snake Gourd (Pathola)",
  "Bottle Gourd (Labu)",
  "Ash Plantain (Alu Kesel)",
  "Winged Beans (Dambala)",
  "Drumstick (Murunga)",
  "Leeks (Leeks)",
  "Beetroot (Rathu ala)",
  "Radish (Rabu)",
  "Spinach (Nivithi)",
  "Amaranth (Thampala)",
  "Okra (Bandakka)",
  "Green Chillies (Amu Miris)",
  "Capsicum (Malumiris)",
  "Onion (Luunu)",
  "Garlic (Sudulunu)",
  "Ginger (Inguru)",
  "Potato (Ala)",
  "Sweet Potato (Bathala)",
  "Yam (Kiri Ala, Raja Ala, Katu Ala)",
  "Cassava (Manyokka)",
  "Kohila (Kohila)",
  "Turmeric (Kaha)",
  "Coriander (Kottamalli)",
  "Fenugreek (Uluhal)",
  "Mint (Minchi)",
  "Curry Leaves (Karapincha)",
  "Water Spinach (Kankun)",
  "Spring Onion (Kola Lunu)",
  "Zucchini (Zucchini)"
];

const fruits = [
  "Banana (Kesel)",
  "Mango (Amba)",
  "Papaya (Papol)",
  "Pineapple (Annasi)",
  "Jackfruit (Waraka)",
  "Durian (Duriyan)",
  "Rambutan (Rambutan)",
  "Mangosteen (Mangus)",
  "Avocado (Aligatapera)",
  "Guava (Pera)",
  "Wood Apple (Diwul)",
  "Soursop (Katu Anoda)",
  "Passion Fruit (Wel Dodam)",
  "Watermelon (Peni Komadu)",
  "Orange (Dodan)",
  "Grapes (Midi)",
  "Pomegranate (Delum)",
  "Lime (Dehi)",
  "Lemon (Lemon)",
  "Apple (Alpple)",
  "Tamarind (Siyambala)",
  "Sapodilla (Sapathilla)",
  "Custard Apple (Anoda)",
  "Starfruit (Kamaranga)",
  "Dragon Fruit",
  "Bellyache Bush (Nelli)",
  "Bilimbi (Bilin)",
  "Pomelo (Jambola)",
  "Rose Apple (Jambu)"
];
